[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
guessing_game = "4XsGy8pPM4wRHBXS37q7PbfUJMK3cY7yAez92MxhEvWi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
